In [4]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [6]:
df.shape

(569, 33)

In [7]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0], test_size=0.2)

In [9]:
y_train

244    M
325    B
239    M
188    B
224    B
      ..
377    B
26     M
465    B
363    B
484    B
Name: diagnosis, Length: 455, dtype: object

In [10]:
X_train.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
244        19.40         23.50          129.10     1155.0          0.10270   
325        12.67         17.30           81.25      489.9          0.10280   
239        17.46         39.28          113.40      920.6          0.09812   
188        11.81         17.39           75.27      428.9          0.10070   
224        13.27         17.02           84.55      546.4          0.08445   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
244           0.15580         0.20490              0.08886         0.1978   
325           0.07664         0.03193              0.02107         0.1707   
239           0.12980         0.14170              0.08811         0.1809   
188           0.05562         0.02353              0.01553         0.1718   
224           0.04994         0.03554              0.02456         0.1496   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
244                 0.06000  ...         21.65          30.53   
325                 0.05984  ...         13.71          21.10   
239                 0.05966  ...         22.51          44.87   
188                 0.05780  ...         12.57          26.48   
224                 0.05674  ...         15.14          23.60   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
244           144.90      1417.0            0.1463             0.2968   
325            88.70       574.4            0.1384             0.1212   
239           141.20      1408.0            0.1365             0.3735   
188            79.57       489.5            0.1356             0.1000   
224            98.84       708.8            0.1276             0.1311   

     concavity_worst  concave points_worst  symmetry_worst  \
244          0.34580               0.15640          0.2920   
325          0.10200               0.05602          0.2688   
239          0.32410               0.20660          0.2853   
188          0.08803               0.04306          0.3200   
224          0.17860               0.09678          0.2506   

     fractal_dimension_worst  
244                  0.07614  
325                  0.06888  
239                  0.08496  
188                  0.06576  
224                  0.07623  

[5 rows x 30 columns]

In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [12]:
X_train

array([[ 1.52880866,  0.95035203,  1.55349863, ...,  0.65027244,
         0.04507521, -0.43098381],
       [-0.40406587, -0.45827598, -0.43298599, ..., -0.87181927,
        -0.34410681, -0.82870887],
       [ 0.97163532,  4.53553751,  0.9017158 , ...,  1.41146993,
        -0.06731787,  0.05220284],
       ...,
       [-0.2403603 ,  0.18469455, -0.19967265, ...,  0.3363922 ,
        -0.08073794,  2.24023854],
       [ 0.69592068, -0.23334989,  0.61941495, ..., -0.3379196 ,
        -0.83729438, -1.05824992],
       [ 0.47477456, -1.82600833,  0.4616586 , ...,  0.48044352,
        -0.56386045, -0.12036382]])

In [13]:
X_train.shape

(455, 30)

In [14]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test  = encoder.transform(y_test)

In [15]:
y_train

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,

In [16]:
y_train.shape

(455,)

In [17]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [18]:
X_train_tensor.shape

torch.Size([455, 30])

In [24]:
import torch
from torch.utils.data import Dataset, DataLoader
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
        # Return one sample and its label
        x = self.features[idx]
        y = self.labels[idx]
        return x, y

In [25]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [26]:
train_dataset[10]

(tensor([ 0.8424,  0.2142,  0.7481,  0.7398, -0.5992, -0.5930, -0.2381,  0.1296,
          0.7750, -1.5315,  0.6695, -0.6538,  0.6319,  0.6540, -0.6449, -0.5962,
         -0.4539, -0.0799,  0.3223, -0.4933,  0.7416, -0.1059,  0.6806,  0.5841,
         -0.8934, -0.6730, -0.3680, -0.0594,  0.6406, -1.0582]),
 tensor(1.))

In [43]:
train_loader = DataLoader(train_dataset,batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32, shuffle=True)

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [30]:
class MySimpleNN():

  def __init__(self,X):

    self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def farward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor * torch.log(y_pred)+ (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [31]:
import torch
import torch.nn as nn
class MyPyTorchNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid

  def farward(self,X):
    z = self.linear(X)
    y_pred = self.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor * torch.log(y_pred)+ (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [32]:
import torch
import torch.nn as nn
class MyPyTorchMultiLayerNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,X):
    z1 = self.linear1(X)
    h1 = self.relu(z1)
    z2 = self.linear2(h1)
    y_pred = self.sigmoid(z2)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor * torch.log(y_pred)+ (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [33]:
import torch
import torch.nn as nn
class MyPyTorchMultiLayerSequentialNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features,3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )


  def forward(self,X):
    y_pred = self.network(X)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor * torch.log(y_pred)+ (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [38]:
import torch
import torch.nn as nn
class MyImprovedNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features,1),
      nn.Sigmoid()
    )

  def forward(self,X):
    y_pred = self.network(X)
    return y_pred

loss_function = nn.BCELoss()


In [35]:
!pip install torchinfo

In [ ]:
model = MyPyTorchMultiLayerNN(X_train_tensor.shape[1])

# call model
# model.farward(X)
model(X_train_tensor.float())

In [ ]:
model.linear1.bias

Parameter containing:
tensor([0.0081, 0.1300, 0.0770], requires_grad=True)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[-0.1254,  0.1732, -0.1213, -0.0521,  0.1490, -0.1064,  0.1101, -0.0161,
          0.1218,  0.0651, -0.1249,  0.1396,  0.0012, -0.0441, -0.1056,  0.0532,
         -0.0940,  0.1654,  0.0054, -0.1636, -0.1539,  0.1264,  0.1136,  0.1276,
          0.1668,  0.0189, -0.1680,  0.1579,  0.0831,  0.1148],
        [-0.0717,  0.0406,  0.1400,  0.1031,  0.0184, -0.1329, -0.1070,  0.1430,
         -0.0873, -0.1457,  0.1075, -0.0804, -0.1643, -0.0197,  0.0031, -0.1419,
          0.1637,  0.1402, -0.0017,  0.1492, -0.1521, -0.1660,  0.0083,  0.0475,
          0.1501, -0.0920, -0.0884,  0.0815, -0.1137,  0.0098],
        [-0.1486, -0.1718,  0.1720, -0.0282,  0.0806, -0.0647,  0.1263, -0.1386,
         -0.0129, -0.0960,  0.0042, -0.1579, -0.1597, -0.1822,  0.0390,  0.0275,
          0.1522,  0.0772, -0.0079, -0.0276, -0.0572,  0.0157, -0.1590,  0.0388,
         -0.1588, -0.0776, -0.1223,  0.0673,  0.1753, -0.1313]],
       requires_grad=True)

In [ ]:
from torchinfo import summary

summary(model,input_size=X_train_tensor.shape)

Layer (type:depth-idx)                   Output Shape              Param #
MyPyTorchMultiLayerNN                    [455, 1]                  --
├─Linear: 1-1                            [455, 3]                  93
├─ReLU: 1-2                              [455, 3]                  --
├─Linear: 1-3                            [455, 1]                  4
├─Sigmoid: 1-4                           [455, 1]                  --
Total params: 97
Trainable params: 97
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.04
Input size (MB): 0.05
Forward/backward pass size (MB): 0.01
Params size (MB): 0.00
Estimated Total Size (MB): 0.07

In [37]:
learning_rate = 0.1
epochs = 25

In [42]:
## training pipeline with data loader

# create model
model = MyImprovedNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)
# loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:
    # farward pass
    y_pred = model(batch_features.float())
    # loss
    loss = loss_function(y_pred,batch_labels.reshape(-1,1).float())
    # clear gradient
    optimizer.zero_grad()

    # backward pass
    loss.backward()
    # update parameters
    # update parameters manually
    optimizer.step()

  #print loss in each epoch
  print(f"Epoch : {epoch+1}, Loss : {loss.item()}")

Epoch : 1, Loss : 0.15204977989196777
Epoch : 2, Loss : 0.15812049806118011
Epoch : 3, Loss : 0.14482608437538147
Epoch : 4, Loss : 0.1509997844696045
Epoch : 5, Loss : 0.024285171180963516
Epoch : 6, Loss : 0.02356891706585884
Epoch : 7, Loss : 0.051072146743535995
Epoch : 8, Loss : 0.06505972146987915
Epoch : 9, Loss : 0.1003856211900711
Epoch : 10, Loss : 0.07626257836818695
Epoch : 11, Loss : 0.0024139073211699724
Epoch : 12, Loss : 0.02645651437342167
Epoch : 13, Loss : 0.08700340986251831
Epoch : 14, Loss : 0.03849829360842705
Epoch : 15, Loss : 0.00552795547991991
Epoch : 16, Loss : 0.14966540038585663
Epoch : 17, Loss : 0.034129779785871506
Epoch : 18, Loss : 0.22700235247612
Epoch : 19, Loss : 0.12434551864862442
Epoch : 20, Loss : 0.1290900558233261
Epoch : 21, Loss : 0.12233620136976242
Epoch : 22, Loss : 0.002248420612886548
Epoch : 23, Loss : 0.0035359219182282686
Epoch : 24, Loss : 0.047462429851293564
Epoch : 25, Loss : 0.005091789178550243


In [44]:
# Model Evaluation using test loader
model.eval() # set model in evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:

    # forward pass
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.9).float() # convert probabilities to binary prediction

    # calculation of accuracy for the current batch
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

# calculate overall accuracy
overall_accuracy = sum(accuracy_list)/len(accuracy_list)
print(f"Accuracy : {overall_accuracy:.4f}")



Accuracy : 0.9019


In [41]:
# create model
model = MyImprovedNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)
# loop
for epoch in range(epochs):

  # farward pass
  y_pred = model(X_train_tensor.float())
  # loss
  loss = loss_function(y_pred,y_train_tensor.reshape(-1,1).float())
  # clear gradient
  optimizer.zero_grad()

  # backward pass
  loss.backward()
  # update parameters
  # update parameters manually
  optimizer.step()

  # print loss in each epoch
  print(f"Epoch : {epoch+1}, Loss : {loss.item()}")

Epoch : 1, Loss : 0.74031662940979
Epoch : 2, Loss : 0.5431771278381348
Epoch : 3, Loss : 0.4403793215751648
Epoch : 4, Loss : 0.3785936236381531
Epoch : 5, Loss : 0.3372257649898529
Epoch : 6, Loss : 0.30740591883659363
Epoch : 7, Loss : 0.2847411334514618
Epoch : 8, Loss : 0.2668190598487854
Epoch : 9, Loss : 0.2522083818912506
Epoch : 10, Loss : 0.24000705778598785
Epoch : 11, Loss : 0.22961832582950592
Epoch : 12, Loss : 0.22063122689723969
Epoch : 13, Loss : 0.21275317668914795
Epoch : 14, Loss : 0.2057700753211975
Epoch : 15, Loss : 0.1995212435722351
Epoch : 16, Loss : 0.19388367235660553
Epoch : 17, Loss : 0.18876142799854279
Epoch : 18, Loss : 0.18407845497131348
Epoch : 19, Loss : 0.1797737330198288
Epoch : 20, Loss : 0.1757974624633789
Epoch : 21, Loss : 0.1721087396144867
Epoch : 22, Loss : 0.16867350041866302
Epoch : 23, Loss : 0.16546322405338287
Epoch : 24, Loss : 0.16245365142822266
Epoch : 25, Loss : 0.15962418913841248


In [ ]:
# create model
model = MySimpleNN(X_train_tensor)

# loop
for epoch in range(epochs):

  # farward pass
  y_pred = model.farward(X_train_tensor)
  # loss
  loss = model.loss_function(y_pred,y_train_tensor)
  # backward pass
  loss.backward()
  # update parameters
  # update parameters manually
  with torch.no_grad():
      model.weights.data -= learning_rate * model.weights.grad
      model.bias.data -= learning_rate * model.bias.grad

  # zero gradients after updating
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f"Epoch : {epoch+1}, Loss : {loss.item()}")

In [ ]:
model.weights

In [ ]:
model.bias

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.farward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy : {accuracy}')

AttributeError: 'MyImprovedNN' object has no attribute 'farward'