In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0], test_size=0.2)

In [6]:
y_train

319    B
334    B
444    M
493    B
542    B
      ..
349    B
57     M
263    M
340    B
144    B
Name: diagnosis, Length: 455, dtype: object

In [7]:
X_train.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
319        12.43         17.00           78.60      477.3          0.07557   
334        12.30         19.02           77.88      464.4          0.08313   
444        18.03         16.85          117.50      990.0          0.08947   
493        12.46         12.83           78.83      477.3          0.07372   
542        14.74         25.42           94.70      668.6          0.08275   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
319           0.03454        0.013420             0.016990         0.1472   
334           0.04202        0.007756             0.008535         0.1539   
444           0.12320        0.109000             0.062540         0.1720   
493           0.04043        0.007173             0.011490         0.1613   
542           0.07214        0.041050             0.030270         0.1840   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
319                 0.05561  ...         12.90          20.21   
334                 0.05945  ...         13.35          28.46   
444                 0.05780  ...         20.38          22.02   
493                 0.06013  ...         13.19          16.36   
542                 0.05680  ...         16.51          32.29   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
319            81.76       515.9           0.08409            0.04712   
334            84.53       544.3           0.12220            0.09052   
444           133.30      1292.0           0.12630            0.26660   
493            83.24       534.0           0.09439            0.06477   
542           107.40       826.4           0.10600            0.13760   

     concavity_worst  concave points_worst  symmetry_worst  \
319          0.02237               0.02832          0.1901   
334          0.03619               0.03983          0.2554   
444          0.42900               0.15350          0.2842   
493          0.01674               0.02680          0.2280   
542          0.16110               0.10950          0.2722   

     fractal_dimension_worst  
319                  0.05932  
334                  0.07207  
444                  0.08225  
493                  0.07028  
542                  0.06956  

[5 rows x 30 columns]

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [9]:
X_train

array([[-0.4539657 , -0.50581967, -0.52099933, ..., -1.27918278,
        -1.6005004 , -1.38717273],
       [-0.49081903, -0.04092546, -0.55061666, ..., -1.10121182,
        -0.5598177 , -0.65700266],
       [ 1.13356224, -0.54034152,  1.07915955, ...,  0.65638673,
        -0.1008336 , -0.07401196],
       ...,
       [ 0.44752338,  0.04192697,  0.35929373, ..., -0.3922658 ,
        -0.35423107, -0.87347661],
       [ 0.11017369, -0.61168667,  0.11865287, ...,  0.46929302,
         0.23543601,  0.23466385],
       [-0.93022408, -0.97301534, -0.94633719, ..., -1.18934687,
        -0.96461617, -0.90783755]])

In [10]:
X_train.shape

(455, 30)

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test  = encoder.transform(y_test)

In [12]:
y_train

array([0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,

In [13]:
y_train.shape

(455,)

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

In [17]:
class MySimpleNN():

  def __init__(self,X):

    self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def farward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor * torch.log(y_pred)+ (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [18]:
learning_rate = 0.1
epochs = 25

In [20]:
# create model
model = MySimpleNN(X_train_tensor)

# loop
for epoch in range(epochs):

  # farward pass
  y_pred = model.farward(X_train_tensor)
  # loss
  loss = model.loss_function(y_pred,y_train_tensor)
  # backward pass
  loss.backward()
  # update parameters
  # update parameters manually
  with torch.no_grad():
      model.weights.data -= learning_rate * model.weights.grad
      model.bias.data -= learning_rate * model.bias.grad

  # zero gradients after updating
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f"Epoch : {epoch+1}, Loss : {loss.item()}")

Epoch : 1, Loss : 3.8036885558688973
Epoch : 2, Loss : 3.688049377101387
Epoch : 3, Loss : 3.5707783816285232
Epoch : 4, Loss : 3.4463022164323527
Epoch : 5, Loss : 3.312014360915669
Epoch : 6, Loss : 3.1733600978755034
Epoch : 7, Loss : 3.0305074904855513
Epoch : 8, Loss : 2.8872527175243623
Epoch : 9, Loss : 2.7351297778354544
Epoch : 10, Loss : 2.5799072236254603
Epoch : 11, Loss : 2.4278707549786622
Epoch : 12, Loss : 2.2765574713069787
Epoch : 13, Loss : 2.1202841172534015
Epoch : 14, Loss : 1.9621155510260866
Epoch : 15, Loss : 1.8089758862011265
Epoch : 16, Loss : 1.6596311962964734
Epoch : 17, Loss : 1.5140646564948834
Epoch : 18, Loss : 1.3805592724768778
Epoch : 19, Loss : 1.2591838458535352
Epoch : 20, Loss : 1.1518637868706605
Epoch : 21, Loss : 1.059882223223958
Epoch : 22, Loss : 0.9856679267259969
Epoch : 23, Loss : 0.9280588146004495
Epoch : 24, Loss : 0.8848373255085432
Epoch : 25, Loss : 0.8531539696992053


In [21]:
model.weights

tensor([[-0.0264],
        [ 0.0731],
        [-0.0849],
        [ 0.1442],
        [-0.2541],
        [ 0.0455],
        [-0.4731],
        [-0.2528],
        [-0.2326],
        [ 0.6836],
        [ 0.4772],
        [ 0.5324],
        [ 0.2855],
        [ 0.5671],
        [-0.1143],
        [ 0.4035],
        [ 0.3499],
        [-0.4708],
        [ 0.0243],
        [-0.3421],
        [-0.5144],
        [ 0.1079],
        [ 0.3324],
        [ 0.1217],
        [ 0.2203],
        [ 0.2898],
        [-0.5352],
        [ 0.2251],
        [ 0.4905],
        [-0.1002]], dtype=torch.float64, requires_grad=True)

In [22]:
model.bias

tensor([-0.1260], dtype=torch.float64, requires_grad=True)

In [25]:
# model evaluation
with torch.no_grad():
  y_pred = model.farward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy : {accuracy}')

Accuracy : 0.549861490726471
