In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
y_train

92     B
228    B
54     M
476    B
318    B
      ..
460    M
249    B
229    M
110    B
263    M
Name: diagnosis, Length: 455, dtype: object

In [ ]:
X_train.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
92        13.270         14.76           84.74      551.7          0.07355   
228       12.620         23.97           81.35      496.4          0.07903   
54        15.100         22.02           97.26      712.8          0.09056   
476       14.200         20.53           92.41      618.4          0.08931   
318        9.042         18.90           60.07      244.5          0.09968   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
92            0.05055         0.03261              0.02648         0.1386   
228           0.07529         0.05438              0.02036         0.1514   
54            0.07081         0.05253              0.03334         0.1616   
476           0.11080         0.05063              0.03058         0.1506   
318           0.19720         0.19750              0.04908         0.2330   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
92                  0.05318  ...         16.36          22.35   
228                 0.06019  ...         14.20          31.31   
54                  0.05684  ...         18.10          31.69   
476                 0.06009  ...         16.45          27.26   
318                 0.08743  ...         10.06          23.40   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
92            104.50       830.6            0.1006             0.1238   
228            90.67       624.0            0.1227             0.3454   
54            117.70      1030.0            0.1389             0.2057   
476           112.10       828.5            0.1153             0.3429   
318            68.62       297.1            0.1221             0.3748   

     concavity_worst  concave points_worst  symmetry_worst  \
92            0.1350                0.1001          0.2027   
228           0.3911                0.1180          0.2826   
54            0.2712                0.1530          0.2675   
476           0.2512                0.1339          0.2534   
318           0.4609                0.1145          0.3135   

     fractal_dimension_worst  
92                   0.06206  
228                  0.09585  
54                   0.07873  
476                  0.07858  
318                  0.10550  

[5 rows x 30 columns]

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.2258905 , -1.04596554, -0.28192943, ..., -0.21672712,
        -1.42237604, -1.18723169],
       [-0.41670528,  1.1081385 , -0.42612307, ...,  0.05477716,
        -0.15315678,  0.63017329],
       [ 0.31132649,  0.65205784,  0.25060872, ...,  0.58565146,
        -0.39302174, -0.29063089],
       ...,
       [-0.35505743,  0.72456297, -0.25981124, ...,  1.26365378,
         0.76976737,  2.16036482],
       [-1.25129978, -0.52439638, -1.22790775, ..., -0.92597519,
        -0.61859012,  0.02939159],
       [ 0.4610427 ,  0.03459479,  0.36715461, ..., -0.43544734,
        -0.38031366, -0.85214933]])

In [ ]:
X_train.shape

(455, 30)

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test  = encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,

In [ ]:
y_train.shape

(455,)

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
class MySimpleNN():

  def __init__(self,X):

    self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def farward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor * torch.log(y_pred)+ (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [ ]:
import torch
import torch.nn as nn
class MyPyTorchNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid

  def farward(self,X):
    z = self.linear(X)
    y_pred = self.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor * torch.log(y_pred)+ (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [ ]:
import torch
import torch.nn as nn
class MyPyTorchMultiLayerNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,X):
    z1 = self.linear1(X)
    h1 = self.relu(z1)
    z2 = self.linear2(h1)
    y_pred = self.sigmoid(z2)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor * torch.log(y_pred)+ (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [ ]:
import torch
import torch.nn as nn
class MyPyTorchMultiLayerSequentialNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features,3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )


  def forward(self,X):
    y_pred = self.network(X)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor * torch.log(y_pred)+ (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [ ]:
import torch
import torch.nn as nn
class MyImprovedNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features,1),
      nn.Sigmoid()
    )

  def forward(self,X):
    y_pred = self.network(X)
    return y_pred

loss_function = nn.BCELoss()


In [ ]:
!pip install torchinfo

In [ ]:
model = MyPyTorchMultiLayerNN(X_train_tensor.shape[1])

# call model
# model.farward(X)
model(X_train_tensor.float())

tensor([[0.4399],
        [0.3949],
        [0.3891],
        [0.4045],
        [0.4167],
        [0.4476],
        [0.4514],
        [0.3857],
        [0.4116],
        [0.4253],
        [0.4588],
        [0.4024],
        [0.4222],
        [0.3858],
        [0.4112],
        [0.4896],
        [0.4978],
        [0.3919],
        [0.3828],
        [0.3929],
        [0.4357],
        [0.3874],
        [0.3880],
        [0.3890],
        [0.4714],
        [0.3775],
        [0.3841],
        [0.4469],
        [0.4540],
        [0.4569],
        [0.3880],
        [0.4528],
        [0.3947],
        [0.4904],
        [0.3828],
        [0.3866],
        [0.3787],
        [0.4774],
        [0.3854],
        [0.4415],
        [0.4173],
        [0.4665],
        [0.4989],
        [0.4862],
        [0.3857],
        [0.4962],
        [0.4667],
        [0.4011],
        [0.4750],
        [0.3847],
        [0.3808],
        [0.4353],
        [0.4464],
        [0.3870],
        [0.3783],
        [0

In [ ]:
model.linear1.bias

Parameter containing:
tensor([0.0081, 0.1300, 0.0770], requires_grad=True)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[-0.1254,  0.1732, -0.1213, -0.0521,  0.1490, -0.1064,  0.1101, -0.0161,
          0.1218,  0.0651, -0.1249,  0.1396,  0.0012, -0.0441, -0.1056,  0.0532,
         -0.0940,  0.1654,  0.0054, -0.1636, -0.1539,  0.1264,  0.1136,  0.1276,
          0.1668,  0.0189, -0.1680,  0.1579,  0.0831,  0.1148],
        [-0.0717,  0.0406,  0.1400,  0.1031,  0.0184, -0.1329, -0.1070,  0.1430,
         -0.0873, -0.1457,  0.1075, -0.0804, -0.1643, -0.0197,  0.0031, -0.1419,
          0.1637,  0.1402, -0.0017,  0.1492, -0.1521, -0.1660,  0.0083,  0.0475,
          0.1501, -0.0920, -0.0884,  0.0815, -0.1137,  0.0098],
        [-0.1486, -0.1718,  0.1720, -0.0282,  0.0806, -0.0647,  0.1263, -0.1386,
         -0.0129, -0.0960,  0.0042, -0.1579, -0.1597, -0.1822,  0.0390,  0.0275,
          0.1522,  0.0772, -0.0079, -0.0276, -0.0572,  0.0157, -0.1590,  0.0388,
         -0.1588, -0.0776, -0.1223,  0.0673,  0.1753, -0.1313]],
       requires_grad=True)

In [ ]:
from torchinfo import summary

summary(model,input_size=X_train_tensor.shape)

Layer (type:depth-idx)                   Output Shape              Param #
MyPyTorchMultiLayerNN                    [455, 1]                  --
├─Linear: 1-1                            [455, 3]                  93
├─ReLU: 1-2                              [455, 3]                  --
├─Linear: 1-3                            [455, 1]                  4
├─Sigmoid: 1-4                           [455, 1]                  --
Total params: 97
Trainable params: 97
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.04
Input size (MB): 0.05
Forward/backward pass size (MB): 0.01
Params size (MB): 0.00
Estimated Total Size (MB): 0.07

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
# create model
model = MyImprovedNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)
# loop
for epoch in range(epochs):

  # farward pass
  y_pred = model(X_train_tensor.float())
  # loss
  loss = loss_function(y_pred,y_train_tensor.reshape(-1,1).float())
  # clear gradient
  optimizer.zero_grad()

  # backward pass
  loss.backward()
  # update parameters
  # update parameters manually
  optimizer.step()

  # print loss in each epoch
  print(f"Epoch : {epoch+1}, Loss : {loss.item()}")

Epoch : 1, Loss : 0.8941565752029419
Epoch : 2, Loss : 0.6246550679206848
Epoch : 3, Loss : 0.4914158284664154
Epoch : 4, Loss : 0.4194013774394989
Epoch : 5, Loss : 0.3733595609664917
Epoch : 6, Loss : 0.34070512652397156
Epoch : 7, Loss : 0.3159896731376648
Epoch : 8, Loss : 0.2964348793029785
Epoch : 9, Loss : 0.2804587185382843
Epoch : 10, Loss : 0.2670859694480896
Epoch : 11, Loss : 0.2556783854961395
Epoch : 12, Loss : 0.2457982897758484
Epoch : 13, Loss : 0.2371339201927185
Epoch : 14, Loss : 0.2294563353061676
Epoch : 15, Loss : 0.2225930392742157
Epoch : 16, Loss : 0.21641099452972412
Epoch : 17, Loss : 0.21080583333969116
Epoch : 18, Loss : 0.20569439232349396
Epoch : 19, Loss : 0.20100924372673035
Epoch : 20, Loss : 0.1966952085494995
Epoch : 21, Loss : 0.19270657002925873
Epoch : 22, Loss : 0.18900512158870697
Epoch : 23, Loss : 0.18555855751037598
Epoch : 24, Loss : 0.18233942985534668
Epoch : 25, Loss : 0.17932423949241638


In [ ]:
# create model
model = MySimpleNN(X_train_tensor)

# loop
for epoch in range(epochs):

  # farward pass
  y_pred = model.farward(X_train_tensor)
  # loss
  loss = model.loss_function(y_pred,y_train_tensor)
  # backward pass
  loss.backward()
  # update parameters
  # update parameters manually
  with torch.no_grad():
      model.weights.data -= learning_rate * model.weights.grad
      model.bias.data -= learning_rate * model.bias.grad

  # zero gradients after updating
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f"Epoch : {epoch+1}, Loss : {loss.item()}")

In [ ]:
model.weights

In [ ]:
model.bias

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.farward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy : {accuracy}')

AttributeError: 'MyImprovedNN' object has no attribute 'farward'