In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU is available!
Using GPU: Tesla T4


Creating Tensors

In [ ]:
torch.empty(2,3)

tensor([[5.0351e-14, 4.4177e-41, 5.0351e-14],
        [4.4177e-41, 5.0351e-14, 4.4177e-41]])

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.2399, 0.9297, 0.1666],
        [0.6703, 0.2045, 0.6936]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [ ]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((5,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# **Tensor Shapes**

In [1]:
import torch
x = torch.tensor([[2,2,4],[5,7,8]])
x
x.shape

torch.Size([2, 3])

In [2]:
torch.empty_like(x)

tensor([[140145650086960, 140145650129904, 140145650144688],
        [140145650081456, 140145650077552, 140145650135920]])

In [3]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [4]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [5]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [6]:
x.dtype

torch.int64

In [7]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [8]:
torch.tensor([1.0,2.0,3.0], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [12]:
x.to(torch.float32)

tensor([[2., 2., 4.],
        [5., 7., 8.]])

In [14]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.0198, 0.4577, 0.9647],
        [0.9169, 0.8593, 0.5016]])

# Math Operation

In [15]:
x = torch.rand(2,3)

In [17]:
x

tensor([[0.9979, 0.8457, 0.9110],
        [0.5439, 0.6433, 0.7298]])

In [16]:
x + 2

tensor([[2.9979, 2.8457, 2.9110],
        [2.5439, 2.6433, 2.7298]])

In [18]:
x - 2

tensor([[-1.0021, -1.1543, -1.0890],
        [-1.4561, -1.3567, -1.2702]])

In [19]:
x * 2

tensor([[1.9959, 1.6913, 1.8220],
        [1.0877, 1.2867, 1.4596]])

In [20]:
x**2

tensor([[0.9959, 0.7151, 0.8299],
        [0.2958, 0.4139, 0.5326]])

In [21]:
x / 3

tensor([[0.3326, 0.2819, 0.3037],
        [0.1813, 0.2144, 0.2433]])

In [22]:
(x * 100) / 3

tensor([[33.2649, 28.1888, 30.3659],
        [18.1283, 21.4447, 24.3271]])

In [23]:
(x * 100) // 3

tensor([[33., 28., 30.],
        [18., 21., 24.]])

In [25]:
((x * 100) // 3) % 2

tensor([[1., 0., 0.],
        [0., 1., 0.]])

Element-wise Operation

In [27]:
a = torch.rand(3,2)
b = torch.rand(3,2)

a + b

tensor([[1.1872, 0.4087],
        [0.6384, 1.3494],
        [1.2352, 1.3613]])

In [28]:
a - b

tensor([[ 0.0853, -0.1948],
        [-0.6206, -0.2048],
        [-0.0725, -0.5087]])

In [29]:
a * b

tensor([[0.3505, 0.0323],
        [0.0056, 0.4447],
        [0.3801, 0.3986]])

In [30]:
a ** b

tensor([[0.7795, 0.5094],
        [0.0511, 0.6481],
        [0.7014, 0.4506]])

In [31]:
a % b

tensor([[0.0853, 0.1070],
        [0.0089, 0.5723],
        [0.5813, 0.4263]])

In [32]:
a // b

tensor([[1., 0.],
        [0., 0.],
        [0., 0.]])

In [34]:
c = torch.tensor([1,-3,-4,-5])

In [35]:
torch.abs(x)

tensor([[0.9979, 0.8457, 0.9110],
        [0.5439, 0.6433, 0.7298]])

In [36]:
torch.neg(x)

tensor([[-0.9979, -0.8457, -0.9110],
        [-0.5439, -0.6433, -0.7298]])

In [37]:
z=torch.tensor([1.3,4.7,6.1,-1.8])
torch.round(z)

tensor([ 1.,  5.,  6., -2.])

In [38]:
torch.ceil(z)

tensor([ 2.,  5.,  7., -1.])

In [39]:
torch.floor(z)

tensor([ 1.,  4.,  6., -2.])

In [41]:
torch.clamp(z,min=2,max=3)

tensor([2., 3., 3., 2.])

## Reduction Operator

In [56]:
e = torch.randint(size=(2,3), low = 0, high =10 , dtype=torch.float32)
e

tensor([[0., 9., 8.],
        [4., 3., 9.]])

In [44]:
torch.sum(e)

tensor(31)

In [45]:
torch.sum(e,dim=0)

tensor([12, 11,  8])

In [46]:
torch.sum(e,dim=1)

tensor([20, 11])

In [47]:
torch.mean(e)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [49]:
torch.mean(e, dtype=torch.float32)

tensor(5.1667)

In [50]:
torch.median(e)

tensor(5)

In [51]:
torch.median(e, dim=0)

torch.return_types.median(
values=tensor([5, 5, 1]),
indices=tensor([1, 1, 1]))

In [52]:
torch.prod(e)

tensor(7350)

In [57]:
torch.std(e)

tensor(3.7283)

In [58]:
torch.var(e)

tensor(13.9000)

In [59]:
torch.argmax(e)

tensor(1)

In [60]:
torch.argmin(e)

tensor(0)

In [63]:
g = torch.randint(size=(2,3), low = 0, high = 10)
g

tensor([[2, 5, 6],
        [3, 3, 8]])

In [64]:
h = torch.randint(size=(3,2), low = 0, high = 10)
h

tensor([[6, 1],
        [6, 8],
        [2, 3]])

In [65]:
torch.matmul(g,h)

tensor([[54, 60],
        [52, 51]])

In [66]:
vector1 = torch.tensor([1,3])
vector2 = torch.tensor([2,4])

In [67]:
torch.dot(vector1,vector2)

tensor(14)

In [68]:
g

tensor([[2, 5, 6],
        [3, 3, 8]])

In [69]:
torch.transpose(g,0,1)

tensor([[2, 3],
        [5, 3],
        [6, 8]])

In [76]:
y = torch.randint(size=(3,3),low = 2 , high = 20 , dtype=torch.float32)
torch.det(y)

tensor(1111.)

In [77]:
torch.inverse(y)

tensor([[ 0.0297,  0.1908, -0.1494],
        [-0.0693, -0.0513,  0.1062],
        [ 0.0495, -0.1971,  0.1449]])

### Special Function

In [85]:
k = torch.randint(size=(2,3), low = 0 , high = 10 , dtype=torch.float32)
k

tensor([[3., 8., 8.],
        [1., 5., 8.]])

In [86]:
# log
torch.log(k)

tensor([[1.0986, 2.0794, 2.0794],
        [0.0000, 1.6094, 2.0794]])

In [87]:
# exp
torch.exp(k)

tensor([[2.0086e+01, 2.9810e+03, 2.9810e+03],
        [2.7183e+00, 1.4841e+02, 2.9810e+03]])

In [88]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 2.8284, 2.8284],
        [1.0000, 2.2361, 2.8284]])

In [89]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9997, 0.9997],
        [0.7311, 0.9933, 0.9997]])

In [90]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.8808, 0.9526, 0.5000],
        [0.1192, 0.0474, 0.5000]])

In [91]:
torch.relu(k)

tensor([[3., 8., 8.],
        [1., 5., 8.]])

In [92]:
torch.tanh(k)

tensor([[0.9951, 1.0000, 1.0000],
        [0.7616, 0.9999, 1.0000]])

In Place Operation

In [93]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1697, 0.0199, 0.5956],
        [0.2044, 0.7708, 0.0940]])
tensor([[0.7205, 0.4803, 0.5294],
        [0.6586, 0.1647, 0.1837]])


In [94]:
m.add_(n)


tensor([[0.8902, 0.5001, 1.1251],
        [0.8630, 0.9354, 0.2776]])

In [95]:
print(m)

tensor([[0.8902, 0.5001, 1.1251],
        [0.8630, 0.9354, 0.2776]])


In [97]:
m.relu_()

tensor([[0.8902, 0.5001, 1.1251],
        [0.8630, 0.9354, 0.2776]])

In [98]:
b = a.clone()

In [100]:
id(b)

140142166799664

In [101]:
id(a)

140142182427120

### Tensor Operation On GPU

In [102]:
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>

In [104]:
device = torch.device('cuda')
device

device(type='cuda')

In [105]:
# creating new tensor in GPU
torch.rand((2,3), device=device)

tensor([[0.6506, 0.5620, 0.0048],
        [0.8557, 0.6084, 0.1648]], device='cuda:0')

In [107]:
# moving the existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.3973, 0.3690, 0.7186],
        [0.1491, 0.6069, 0.8219]])

In [110]:
b=a.to(device=device)
b

tensor([[0.3973, 0.3690, 0.7186],
        [0.1491, 0.6069, 0.8219]], device='cuda:0')

In [111]:
b + 2

tensor([[2.3973, 2.3690, 2.7186],
        [2.1491, 2.6069, 2.8219]], device='cuda:0')

In [115]:
import time
import torch

size = 10000

matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size,size)

start_time = time.time()
result_cpu=torch.matmul(matrix_cpu1,matrix_cpu2)

cpu_time = time.time() - start_time

print(f"Time on CPU : {cpu_time:.4f} seconds")

matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start_time = time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"Time on GPU : {gpu_time:.4f} seconds")

Time on CPU : 26.0029 seconds
Time on GPU : 0.4880 seconds


## Reshaping the tensor

In [4]:
import torch
a = torch.rand(4,4)
a

tensor([[0.2819, 0.3699, 0.2935, 0.3422],
        [0.7444, 0.3637, 0.6960, 0.4584],
        [0.3860, 0.5325, 0.7611, 0.8023],
        [0.5476, 0.6708, 0.2717, 0.8592]])

In [5]:
# reshape
b=a.reshape(2,2,2,2)

print(torch.prod(a))
print(torch.prod(b))


tensor(9.7318e-06)
tensor(9.7318e-06)


In [6]:
# flatten
a.flatten()

tensor([0.2819, 0.3699, 0.2935, 0.3422, 0.7444, 0.3637, 0.6960, 0.4584, 0.3860,
        0.5325, 0.7611, 0.8023, 0.5476, 0.6708, 0.2717, 0.8592])

In [9]:
b = torch.rand(2,3,4)
b

tensor([[[0.7421, 0.4285, 0.8357, 0.3287],
         [0.7672, 0.5370, 0.6002, 0.1675],
         [0.7005, 0.4364, 0.5608, 0.8253]],

        [[0.0666, 0.1355, 0.4098, 0.5884],
         [0.3132, 0.5306, 0.3065, 0.3024],
         [0.9473, 0.0267, 0.3455, 0.5491]]])

In [13]:
# permute
p = b.permute(2,1,0)
p.shape

torch.Size([4, 3, 2])

In [15]:
# unsequeeze
image=torch.rand(256,256,3)
# convert to image batch
image.unsqueeze_(0)
image.shape


torch.Size([1, 256, 256, 3])

In [18]:
# sequeeze
image.squeeze_(0)
image.shape

torch.Size([256, 256, 3])

## NumPy and PyTorch

In [24]:
import numpy as np

a = torch.tensor([2,3,4,5])
print(type(a))
b = a.numpy()
print(type(b))
c = torch.from_numpy(b)
print(type(c))


<class 'torch.Tensor'>
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
