# Linear Regression

In [35]:
# house pricing dataset
from sklearn.datasets import fetch_california_housing

In [36]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib

Using matplotlib backend: module://matplotlib_inline.backend_inline


In [37]:
df=fetch_california_housing()

In [38]:
df

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': 

In [39]:
dataset=pd.DataFrame(df.data)
dataset.columns=df.feature_names
dataset.head()

MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0  8.3252      41.0  6.984127  ...  2.555556     37.88    -122.23
1  8.3014      21.0  6.238137  ...  2.109842     37.86    -122.22
2  7.2574      52.0  8.288136  ...  2.802260     37.85    -122.24
3  5.6431      52.0  5.817352  ...  2.547945     37.85    -122.25
4  3.8462      52.0  6.281853  ...  2.181467     37.85    -122.25

[5 rows x 8 columns]

In [40]:
dataset['Price']=df.target
dataset.head()

MedInc  HouseAge  AveRooms  AveBedrms  ...  AveOccup  Latitude  Longitude  Price
0  8.3252      41.0  6.984127   1.023810  ...  2.555556     37.88    -122.23  4.526
1  8.3014      21.0  6.238137   0.971880  ...  2.109842     37.86    -122.22  3.585
2  7.2574      52.0  8.288136   1.073446  ...  2.802260     37.85    -122.24  3.521
3  5.6431      52.0  5.817352   1.073059  ...  2.547945     37.85    -122.25  3.413
4  3.8462      52.0  6.281853   1.081081  ...  2.181467     37.85    -122.25  3.422

[5 rows x 9 columns]

In [41]:
# independent feature
X=dataset.iloc[:,:-1]
# dependent feature
y=dataset.iloc[:,-1]


In [50]:
# Linear Regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
lin_reg=LinearRegression()
mse=cross_val_score(lin_reg,X,y,scoring='neg_mean_squared_error',cv=5)
mse

array([-7.87100281e-01, -2.63706195e+01, -2.56742262e-04, -1.30742639e-03,
       -1.61912499e-03])

In [ ]:
mean_mse=np.mean(mse)
print(mean_mse)

-0.5582901717686573


In [44]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Sample dataset
data = {
    "MedInc": [8.3252, 8.3014, 7.2574, 5.6431, 3.8462],
    "HouseAge": [41.0, 21.0, 52.0, 52.0, 52.0],
    "AveRooms": [6.984127, 6.238137, 8.288136, 5.817352, 6.281853],
    "AveBedrms": [1.023810, 0.971880, 1.073446, 1.073059, 1.081081],
    "Population": [322.0, 2401.0, 496.0, 558.0, 565.0],
    "AveOccup": [2.555556, 2.109842, 2.802260, 2.547945, 2.181467],
    "Latitude": [37.88, 37.86, 37.85, 37.85, 37.85],
    "Longitude": [-122.23, -122.22, -122.24, -122.25, -122.25],
    "Price": [4.526, 3.585, 3.521, 3.413, 3.422]
}

df = pd.DataFrame(data)

# Features and target
X = df.drop("Price", axis=1)
y = df["Price"]

# Train model
model = LinearRegression()
model.fit(X, y)

# Predict using a new sample (e.g., row 0)
new_data = np.array([[8.3252, 41.0, 6.984127, 1.023810, 322.0, 2.555556, 37.88, -122.23]])
prediction = model.predict(new_data)

print(f"Predicted Price: {prediction[0]:.3f}")

Predicted Price: 4.526


/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [61]:
# Train model
linear_reg = LinearRegression().fit(X, y)

In [62]:
# Predict using a new sample (e.g., row 0)
new_data = np.array([[8.3252, 41.0, 6.984127, 1.023810, 322.0, 2.555556, 37.88, -122.23]])
prediction = linear_reg.predict(new_data)

print(f"Linear Regression - Predicted Price: {prediction[0]:.3f}")

Linear Regression - Predicted Price: 4.526


/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [ ]:
linear_reg.score(X, y)

1.0

In [ ]:
linear_reg.coef_

array([-0.00416229, -0.07522031,  0.01749425, -0.00020896, -0.00117095,
       -0.00434675,  0.00015575,  0.00014159])

In [ ]:
linear_reg.intercept_

np.float64(7.922276197065116)

# Ridge Regression

In [54]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
ridge=Ridge()
params={"alpha":[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20]}

ridge_regressor=GridSearchCV(ridge,params,scoring='neg_mean_squared_error',cv=5)
ridge_regressor.fit(X,y)

/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:252: LinAlgWarning: Ill-conditioned matrix (rcond=1.49299e-17): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:254: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn(
/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:252: LinAlgWarning: Ill-conditioned matrix (rcond=4.03716e-17): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:252: LinAlgWarning: Ill-conditioned matrix (rcond=3.43614e-18): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/opt/miniconda3/envs/agentic_env/l

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20]},
             scoring='neg_mean_squared_error')

In [57]:
print(ridge_regressor.best_params_)
print(ridge_regressor.best_score_)

{'alpha': 1e-15}
-5.432180613591023


In [55]:
# Predict using a new sample (e.g., row 0)
new_data = np.array([[8.3252, 41.0, 6.984127, 1.023810, 322.0, 2.555556, 37.88, -122.23]])
prediction = ridge_regressor.predict(new_data)

print(f"Ridge Regression - Predicted Price: {prediction[0]:.3f}")

Ridge Regression - Predicted Price: 4.526


/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


## Lasso Regession

In [59]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
ridge=Lasso()
params={"alpha":[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20]}

lasso_regressor=GridSearchCV(ridge,params,scoring='neg_mean_squared_error',cv=5)
lasso_regressor.fit(X,y)

/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.872e-04, tolerance: 8.498e-05
  model = cd_fast.enet_coordinate_descent(
/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.692e-04, tolerance: 7.887e-05
  model = cd_fast.enet_coordinate_descent(
/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider in

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20]},
             scoring='neg_mean_squared_error')

In [60]:
print(lasso_regressor.best_params_)
print(lasso_regressor.best_score_)

{'alpha': 0.01}
-0.7428396613590845


In [63]:
# Predict using a new sample (e.g., row 0)
new_data = np.array([[8.3252, 41.0, 6.984127, 1.023810, 322.0, 2.555556, 37.88, -122.23]])
prediction = lasso_regressor.predict(new_data)

print(f"Ridge Regression - Predicted Price: {prediction[0]:.3f}")

Ridge Regression - Predicted Price: 4.524


/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(


# Logistic Regression 

In [ ]:
from sklearn.linear_model import LogisticRegression
# load dataset
from sklearn.datasets import load_breast_cancer
df=load_breast_cancer()
#Independent Features
X=pd.DataFrame(df['data'],columns=df['feature_names'])

In [66]:
X.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [67]:
#Dependent Features
y=pd.DataFrame(df['target'],columns=['Target'])
y

Target
0         0
1         0
2         0
3         0
4         0
..      ...
564       0
565       0
566       0
567       0
568       1

[569 rows x 1 columns]

In [68]:
# check if data balanced
y['Target'].value_counts()

Target
1    357
0    212
Name: count, dtype: int64

In [69]:
# train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [71]:
params=[{'C':[1,5,10]},{'max_iter':[100,150]}]
logistic=LogisticRegression(C=100,max_iter=100)
logistic_regression=GridSearchCV(logistic,param_grid=params,scoring='f1',cv=5)
logistic_regression.fit(X_train,y_train)

/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/miniconda3/envs/agentic_env/lib/python3.11/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Plea

GridSearchCV(cv=5, estimator=LogisticRegression(C=100),
             param_grid=[{'C': [1, 5, 10]}, {'max_iter': [100, 150]}],
             scoring='f1')

In [72]:
print(logistic_regression.best_params_)
print(logistic_regression.best_score_)

{'max_iter': 150}
0.9598489022094405


In [73]:
y_pred=logistic_regression.predict(X_test)

In [ ]:
# calculate R2 & Adjusted R2 for others
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Example usage:
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)

#calculate Adj R2
n= len(X_train)
p = len(X.columns)
adj_R2 = 1- ((1-R2) * (n-1)/(n-p-1)) #Adj R2 = 1-(1-R2)*(n-1)/(n-p-1)


print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("R2 Score:", R2)
print("Adjusted R2 Score:", adj_R2)



Mean Squared Error: 0.031914893617021274
Mean Absolute Error: 0.031914893617021274
R2 Score: 0.8608609843345257
Adjusted R2 Score: 0.8489347829917708


In [77]:
# confusion matrix
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
confusion_matrix(y_test,y_pred)

array([[ 64,   3],
       [  3, 118]])

In [78]:
accuracy_score(y_test,y_pred)

0.9680851063829787

In [80]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96        67
           1       0.98      0.98      0.98       121

    accuracy                           0.97       188
   macro avg       0.97      0.97      0.97       188
weighted avg       0.97      0.97      0.97       188

